* Include config.h before the C library headers, because it defines   _FILE_OFFSET_BITS=64.  Without it, functions like stat() fail on   large file sizes.  This happened with a Nix store on squashfs:
  $ nix-store --dump /tmp/mnt/46wzqnk4cbdwh1dclhrpqnnz1icak6n7-local-net-cmds > /dev/null
  error: getting attributes of path `/tmp/mnt/46wzqnk4cbdwh1dclhrpqnnz1icak6n7-local-net-cmds': Value too large for defined data type

  $ stat /tmp/mnt/46wzqnk4cbdwh1dclhrpqnnz1icak6n7-local-net-cmds
  File: `/tmp/mnt/46wzqnk4cbdwh1dclhrpqnnz1icak6n7-local-net-cmds'
  Size: 0               Blocks: 36028797018963968 IO Block: 1024   regular empty file

  (This is a bug in squashfs or mksquashfs, but it shouldn't cause Nix
  to fail.)


git-svn-id: https://svn.nixos.org/repos/nix/nix/trunk@19016 70bd8c7a-acb8-0310-9f0d-9cc1c95dcdbb